name: Daily Naval Monitor

on:
  schedule:
    # Runs at 08:00 UTC every day
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab for testing

permissions:
  contents: write

jobs:
  scrape-and-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Monitor Script
        run: python monitor_navies.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/tweets.json README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated Data Update: $(date +'%Y-%m-%d')" && git push)