name: Daily Naval Monitor

on:
  schedule:
    - cron: '0 8 * * *' # Runs daily at 8am UTC
  workflow_dispatch:      # Allows manual run button
  push:                   # Runs immediately when you save this file
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  scrape-and-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 pandas

      - name: Run Monitor Script
        run: python monitor_navies.py

      - name: Commit and Push Changes
        # This step will only run if there are changes to commit
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/tweets.json README.md
          # Check if there are changes before committing to avoid errors
          if [[ -n $(git status -s) ]]; then
            git commit -m "Automated Data Update: $(date +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit today."
          fi